<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWiOlYGE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWiOlYGE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWiOlYGE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWiOlYGE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWiOlYGE\App_KernelDevDebugContainer([
    'container.build_hash' => 'WiOlYGE',
    'container.build_id' => '40a39a4c',
    'container.build_time' => 1654596460,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWiOlYGE');
