<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ4feEl0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ4feEl0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ4feEl0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ4feEl0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ4feEl0\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q4feEl0',
    'container.build_id' => '70fc440a',
    'container.build_time' => 1654251244,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ4feEl0');
