<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_init_index' => [[], ['_controller' => 'App\\Controller\\InitController::index'], [], [['text', '/']], [], [], []],
    'app_init_indexi' => [['_locale'], ['_controller' => 'App\\Controller\\InitController::indexi'], [], [['variable', '/', '[^/]++', '_locale', true]], [], [], []],
];
